### ISSUE TITLE
Recommendation Algorithm

### ISSUE THREAD

**Issue by dabadav** [rrrajjjj/recsys-simulation#4]
### Algorithm

Considered factors:
- Patient protocol fit (PPF)
- Patient history 
    - Adherence (completed_duration/prescribed_duration)-per protocol
    - Recent performance 
    - Recent dm changes 
    - novelty of the protocol
    - associations of protocols with subjective assessment 
- current mood/motivation (from subjective assessment)
    - if the patient is tired, unmotivated etc. we can give them protocols with high previous mood associations, and high previous dm changes (relatively easy).

**Scoring Function**

$$ Score = a \cdot PPF + b \cdot \Delta dm + c \cdot associtation_{subj} + d \cdot adherence$$

**Protocol Sampling**

Turn the distribution closer to softmax the more tired, unmotivated the person is. 

$$dist_{modified} = \frac{(15-score_{subjective})*softmax(dist_{original}) + dist_{original}}{15}$$

### TODO

**Documentation**

- [x] Documentation for high level understanding (clinical interpretation of the algorithm) - @rrrajjjj 

**Implementation**

 - [x] Expand `Session`, `Protocol`, `Patient` classes to meet real RGS logs. - @dabadav 
 - [x] Update scoring function to include new factors - @dabadav 
 - [x] Softmax protocol sampling based on current mood  - @rrrajjjj

**Comment by dabadav** [comment]
This PR #6 addresses the following:
- Task 1: Expanded classes to adapt to real RGS data.
- Task 2: Updated the scoring function to include PPF, delta DM, and adherence.
